name: release
on:
  workflow_dispatch: { }

env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

jobs:
  purge_workflow_runs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Setup
        run: sudo apt-get install -y jq
      - env:
          GH_TOKEN: ${{ github.token }}
        name: Purge
        run: |
          gh api repos/TonyBogdanov/rife-ncnn-vulkan/actions/runs --paginate |\
          jq '.workflow_runs[] | .id' |\
          xargs -t -I{} sh -c "gh api -X DELETE /repos/TonyBogdanov/rife-ncnn-vulkan/actions/runs/{} || true"

  windows:
    runs-on: windows-latest
    env:
      PACKAGENAME: rife-ncnn-vulkan
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: cache-vulkansdk
        id: cache-vulkansdk
        uses: actions/cache@v1
        with:
          path: "VulkanSDK"
          key: VulkanSDK-1.2.198.1-Installer
      - name: vulkansdk
        if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.2.198.1/windows/VulkanSDK-1.2.198.1-Installer.exe?Human=true -OutFile VulkanSDK-1.2.198.1-Installer.exe
          7z x -aoa ./VulkanSDK-1.2.198.1-Installer.exe -oVulkanSDK
          Remove-Item .\VulkanSDK\Demos, .\VulkanSDK\Tools -Recurse
      - name: build
        run: |
          $env:VULKAN_SDK="$(pwd)/VulkanSDK"
          mkdir build; cd build
          cmake -A x64 ../src
          cmake --build . --config Release -j 2
      - name: package
        run: |
          mkdir rife-ncnn-vulkan
          Copy-Item -Verbose -Path "build\Release\rife-ncnn-vulkan.exe" -Destination "rife-ncnn-vulkan"
          Copy-Item -Verbose -Path "C:\windows\system32\vcomp140.dll" -Destination "rife-ncnn-vulkan"
          Copy-Item -Verbose -Recurse -Path "models\*" -Destination "rife-ncnn-vulkan"
          7z a -r rife-ncnn-vulkan.zip rife-ncnn-vulkan
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: rife-ncnn-vulkan
          path: rife-ncnn-vulkan.zip
